# Use `conda-build-prepare` before building for a better version string.
{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: odin_ii
  version: {{ version }}

source:
  git_url: https://github.com/verilog-to-routing/vtr-verilog-to-routing

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libxml2 >2.9.9
    - bison
    - cmake
    - flex
    - fontconfig
    - ncurses
    - pkg-config
    - tk
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxcb
    - xorg-libxext
    - xorg-libxft
    - tbb <2021.0.0a0
    - tbb-devel <2021.0.0a0
    - gtk3
  run:
    - tbb <2021.0.0a0

about:
  home: http://verilogtorouting.org/
  license: MIT
  license_file: LICENSE.md
  summary: 'Odin II is used for logic synthesis and elaboration, converting a subset of the Verilog Hardware Description Language (HDL) into a BLIF netlist.'
