{% set version = "1.5.0" %}

package:
  name: libunwind
  version: {{ version }}

source:
  url: http://download.savannah.nongnu.org/releases/libunwind/libunwind-{{ version }}.tar.gz
  sha256: 90337653d92d4a13de590781371c604f9031cdb50520366aa1e3a91e1efb1017

build:
  number: {{ environ.get('DATE_NUM') }}
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
  run_exports:
    - {{ pin_subpackage('libunwind', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - libtool
  host:

test:
  commands:
    - test -f "${PREFIX}/lib/libunwind.so"
    - test ! -f "${PREFIX}/lib/libunwind.a"
    - test -f "${PREFIX}/include/libunwind.h"
    - test -f "${PREFIX}/include/unwind.h"
