name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 67
defaults:
  run:
    shell: bash
jobs:

  #9
  yosys-linux-py37:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #10
  yosys-linux-py38:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #11
  yosys-plugins-symbiflow-linux:
    runs-on: "ubuntu-20.04"
    needs: ["yosys-linux-py37", "yosys-linux-py38"]
    env:
      PACKAGE: "syn/yosys-plugins-symbiflow"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #15
  symbiflow-yosys-plugins-linux:
    runs-on: "ubuntu-20.04"
    needs: ["yosys-linux-py37"]
    env:
      PACKAGE: "syn/symbiflow-yosys-plugins"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #35
  yosys-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "osx"
      EXTRA_BUILD_ARGS: "--no-test"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

  #46
  yosys-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
      - uses: hdl/conda-ci@master

