name: build-packages
on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/workflows/tuttest.yml'
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 71
defaults:
  run:
    shell: bash
jobs:
  #6
  icarus-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sim/icarus"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #8
  yosys-linux-py37:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.7"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #64
  yosys-linux-py38:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "syn/yosys"
      OS_NAME: "linux"
      PYTHON_VERSION: "3.8"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

  #71
  yosys-plugins-symbiflow-linux:
    runs-on: "ubuntu-16.04"
    needs: ["icarus-linux", "yosys-linux-py37", "yosys-linux-py38"]
    env:
      PACKAGE: "syn/yosys-plugins-symbiflow"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: hdl/conda-ci@master

